### ISSUE TITLE
"context deadline exceeded" with consecutive requests

### ISSUE THREAD

**Issue by NiklasBr** [gotenberg/gotenberg#577]
```yaml
  gotenberg:
      image: gotenberg/gotenberg:7.7
      ports:
          - "3000:3000"
      command: [
          gotenberg,
          --chromium-ignore-certificate-errors=true,
          --chromium-disable-web-security,
          --uno-listener-restart-threshold=0
      ]
```

With the following code:
```php
$partialDocuments = [];
foreach ($document->getAllChildren() as $child) {
    $html = $document->renderDocument($params);
    $request = Gotenberg::chromium($this->baseUri)->html(
        Stream::string($child->getPdfFileName() . '--transient.html', $html)
    );
    $partialDocuments[] = Gotenberg::save($request, SYSTEM_TEMP_DIRECTORY . DIRECTORY_SEPARATOR);
    sleep(2);
}
```
Next step is to merge the separate PDF:s but cannot reach it because the third `$child` crashes Gotenberg.

```log
2022-11-18 15:00:31 {"level":"info","ts":1668780031.5957,"logger":"api","msg":"request handled","trace":"2f01838c-53b2-4d19-a0ad-b005cd94b324","remote_ip":"172.18.0.10","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Symfony HttpClient/Curl","status":200,"latency":2557421751,"latency_human":"2.557421751s","bytes_in":4011,"bytes_out":18070}
2022-11-18 15:00:47 {"level":"info","ts":1668780047.2433655,"logger":"api","msg":"request handled","trace":"4e0f0f1c-f587-4756-ae79-eccc3da6b5bb","remote_ip":"172.18.0.10","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Symfony HttpClient/Curl","status":200,"latency":2398633335,"latency_human":"2.398633335s","bytes_in":8009,"bytes_out":18448}
2022-11-18 15:01:28 {"level":"error","ts":1668780088.1366816,"logger":"api","msg":"convert HTML to PDF: convert to PDF: chromium PDF: wait for events: wait for event networkIdle: context deadline exceeded","trace":"bf54e5fc-ad6b-4f28-b8ca-f6f41f2e3386","remote_ip":"172.18.0.10","host":"gotenberg:3000","uri":"/forms/chromium/convert/html","method":"POST","path":"/forms/chromium/convert/html","referer":"","user_agent":"Symfony HttpClient/Curl","status":503,"latency":30012295722,"latency_human":"30.012295722s","bytes_in":11648,"bytes_out":19}
```

The PHP exception is:
```
"Gotenberg\Exceptions\GotenbergApiErroed: Service Unavailable in vendor/gotenberg/gotenberg-php/src/Exceptions/GotenbergApiErroed.php:16
Stack trace:
#0 vendor/gotenberg/gotenberg-php/src/Gotenberg.php(55): Gotenberg\Exceptions\GotenbergApiErroed::createFromResponse(Object(GuzzleHttp\Psr7\Response))
gotenberg/gotenberg-php#1 vendor/gotenberg/gotenberg-php/src/Gotenberg.php(71): Gotenberg\Gotenberg::send(Object(GuzzleHttp\Psr7\Request), Object(Symfony\Component\HttpClient\Psr18Client))
gotenberg/gotenberg-php#2 GotenbergPhp.php(182): Gotenberg\Gotenberg::save(Object(GuzzleHttp\Psr7\Request), '/var/www/...')
gotenberg/gotenberg#394 GotenbergPhp->buildPdf(Object(\Document\Printpage), Object(stdClass))
gotenberg/gotenberg-php#4 Processor.php(130): Web2Print\Processor\GotenbergPhp->buildPdf(Object("
```

**Comment by vidklopcic** [comment]
I can also confirm that this happens with version `7.8.0` on a machine with more than enough resources. If I use `7.4.2` it works normally.

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
```
A Docker-powered stateless API for PDF files.
Version: 7.8.0
-------------------------------------------------------
[SYSTEM] modules: api chromium gc libreoffice logging pdfcpu pdfengines pdftk prometheus qpdf uno uno-pdfengine webhook 
[SYSTEM] prometheus: collecting metrics
[SYSTEM] gc: application started
[SYSTEM] uno: long-running LibreOffice listener ready to start
[SYSTEM] pdfengines: pdfcpu pdftk qpdf uno-pdfengine
[SYSTEM] api: server listening on port 3000
{"level":"error","ts":1674551185.839853,"logger":"api","msg":"convert to PDF: lock long-running LibreOffice listener: start long-running LibreOffice listener: execute LibreOffice listener: context done: context deadline exceeded","trace":"6eef1be1-7f0f-48f6-b5ad-f349b5ae7e52","remote_ip":"172.40.13.4","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-requests/2.28.2","status":503,"latency":10001830810,"latency_human":"10.00183081s","bytes_in":14665,"bytes_out":19}
```

**Comment by NiklasBr** [comment]
I don't know what else I can contribute with in this issue. Could never resolve it on my own.

**Comment by gulien** [comment]
Closing this for now. Feel free to reopen this issue if it happens with the latest version.

**Comment by lippoliv** [comment]
Today I saw a issue that looks familiar to yours. I'm running gotenberg for paperlessngx on a Synology DS918+. I was able to fix it with defining `libreoffice-start-timeout`. 

Disclaimer: Currently one mail that repetitively failed was now processed successfully. I'm still testing as time goes by. 

```yml
  gotenberg:
    image: gotenberg/gotenberg:8.8.1
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
      - "--api-timeout=900s"
      - "--libreoffice-start-timeout=60s"
      - "--log-level=debug"
`
``
