### ISSUE TITLE
Error while converting document to PDF: Server error '503 Service Unavailable'

### ISSUE THREAD

**Issue by steakhutzeee** [gotenberg/gotenberg#720]
Hi,

i'm running paperless-ngx with default configuration for tika and gotenberg as per official compose file https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres-tika.yml

Of course my volumes etc. are different.

I tried consuming a .docx file and got this output:

```
xxx.docx
Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert' For more information check: https://httpstatuses.com/503


11/18/2023
04:58:16 PM
[2023-11-18 16:58:16,760] [INFO] [paperless.consumer] Consuming xxx.docx
11/18/2023
04:58:17 PM
[2023-11-18 16:58:17,583] [INFO] [paperless.parsing.tika] Sending /tmp/paperless/paperless-ngx2087ozu2/xxx.docx to Tika server
11/18/2023
04:58:26 PM
[2023-11-18 16:58:26,428] [INFO] [paperless.parsing.tika] Converting /tmp/paperless/paperless-ngx2087ozu2/xxx.docx to PDF as /tmp/paperless/paperless-rcmbspao/convert.pdf
11/18/2023
04:58:38 PM
[2023-11-18 16:58:38,042] [ERROR] [paperless.consumer] Error occurred while consuming document xxx.docx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
11/18/2023
04:58:38 PM
Traceback (most recent call last):
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 105, in convert_to_pdf
11/18/2023
04:58:38 PM
    response.raise_for_status()  # ensure we notice bad responses
11/18/2023
04:58:38 PM
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
11/18/2023
04:58:38 PM
    raise HTTPStatusError(message, request=request, response=self)
11/18/2023
04:58:38 PM
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
The above exception was the direct cause of the following exception:
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
Traceback (most recent call last):
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
11/18/2023
04:58:38 PM
    document_parser.parse(self.path, mime_type, self.filename)
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 70, in parse
11/18/2023
04:58:38 PM
    self.archive_path = self.convert_to_pdf(document_path, file_name)
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 107, in convert_to_pdf
11/18/2023
04:58:38 PM
    raise ParseError(
11/18/2023
04:58:38 PM
documents.parsers.ParseError: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
11/18/2023
04:58:38 PM
[2023-11-18 16:58:38,361] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[022a12cc-2501-44d2-91e5-21dde73861a4] raised unexpected: ConsumerError("xxx.docx: Error occurred while consuming document xxx.docx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'\nFor more information check: https://httpstatuses.com/503")
11/18/2023
04:58:38 PM
Traceback (most recent call last):
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 105, in convert_to_pdf
11/18/2023
04:58:38 PM
    response.raise_for_status()  # ensure we notice bad responses
11/18/2023
04:58:38 PM
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
11/18/2023
04:58:38 PM
    raise HTTPStatusError(message, request=request, response=self)
11/18/2023
04:58:38 PM
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
The above exception was the direct cause of the following exception:
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
Traceback (most recent call last):
11/18/2023
04:58:38 PM
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 349, in main_wrap
11/18/2023
04:58:38 PM
    raise exc_info[1]
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
11/18/2023
04:58:38 PM
    document_parser.parse(self.path, mime_type, self.filename)
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 70, in parse
11/18/2023
04:58:38 PM
    self.archive_path = self.convert_to_pdf(document_path, file_name)
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/paperless_tika/parsers.py", line 107, in convert_to_pdf
11/18/2023
04:58:38 PM
    raise ParseError(
11/18/2023
04:58:38 PM
documents.parsers.ParseError: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
The above exception was the direct cause of the following exception:
11/18/2023
04:58:38 PM
11/18/2023
04:58:38 PM
Traceback (most recent call last):
11/18/2023
04:58:38 PM
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
11/18/2023
04:58:38 PM
    R = retval = fun(*args, **kwargs)
11/18/2023
04:58:38 PM
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
11/18/2023
04:58:38 PM
    return self.run(*args, **kwargs)
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/documents/tasks.py", line 156, in consume_file
11/18/2023
04:58:38 PM
    document = Consumer().try_consume_file(
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/documents/consumer.py", line 453, in try_consume_file
11/18/2023
04:58:38 PM
    self._fail(
11/18/2023
04:58:38 PM
  File "/usr/src/paperless/src/documents/consumer.py", line 109, in _fail
11/18/2023
04:58:38 PM
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
11/18/2023
04:58:38 PM
documents.consumer.ConsumerError: xxx.docx: Error occurred while consuming document xxx.docx: Error while converting document to PDF: Server error '503 Service Unavailable' for url 'http://gotenberg:3000/forms/libreoffice/convert'
11/18/2023
04:58:38 PM
For more information check: https://httpstatuses.com/503
```

I tried increasing the api timeout and also changing the tika/gotenberg endpoints to "localhost" and "server-ip" without luck.

Any idea?

**Comment by gulien** [comment]
Hello @steakhutzeee,

How large is your `.docx` document?

**Comment by steakhutzeee** [comment]
Hi gulien! You mean the size of the file? If yes its 56KB. But i tried also with a dummy file with just a string in it.

**Comment by gulien** [comment]
LibreOffice does struggle with « large » file, but in your case it’s not that lol

Could you try with the `edge` version of Gotenberg?

**Comment by steakhutzeee** [comment]
Got same issue also with edge version.

Gotenberg logs:

```
[SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook 
[SYSTEM] chromium: Chromium ready to start
[SYSTEM] prometheus: collecting metrics
[SYSTEM] libreoffice-api: LibreOffice ready to start
[SYSTEM] api: server listening on port 3000
[SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
{"level":"warn","ts":1700439320.185543,"logger":"api.formslibreofficeconvert","msg":"'pdfFormat' is deprecated; prefer the 'pdfa' form field instead","trace":"cdd99d09-9e0c-42b0-9de8-addab6e863d9"}
2023-11-20T00:15:30.450046611Z {"level":"error","ts":1700439330.4471874,"logger":"api","msg":"convert to PDF: process first start: start process: execute LibreOffice: context done: context deadline exceeded","trace":"cdd99d09-9e0c-42b0-9de8-addab6e863d9","remote_ip":"172.18.0.15","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-httpx/0.24.1","status":503,"latency":10365052284,"latency_human":"10.365052284s","bytes_in":56989,"bytes_out":19}
```

**Comment by gulien** [comment]
Thanks! It looks like LibreOffice is struggling to startup. Could you increase the start timeout with `--libreoffice-start-timeout=30s`?

**Comment by gulien** [comment]
Yes sorry, in `edge` the flag ` --uno-listener-start-timeout` has been deprecated. 

Now LibreOffice is able to start, but it fails to convert your document under 30 seconds. You may either increase the timeout with `--api-timeout=300s`, maybe that will help. Does it work using the demo, i.e., https://demo.gotenberg.dev?

**Comment by steakhutzeee** [comment]
> Yes sorry, in `edge` the flag `--uno-listener-start-timeout` has been deprecated.
> 
> Now LibreOffice is able to start, but it fails to convert your document under 30 seconds. You may try to increase the timeout with `--api-timeout=300s`, maybe that will help. Also, does your conversion works using the demo, i.e., https://demo.gotenberg.dev?

The logs above are from version 7.8. Switched back to it after edge gave me the same error. So what i should try and which command?

Thanks!

**Comment by gulien** [comment]
Could you try using the demo API please?

**Comment by steakhutzeee** [comment]
> Could you try using the demo API please?

Actually my compose file has `PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000`. I can just change this to `PAPERLESS_TIKA_GOTENBERG_ENDPOINT: https://demo.gotenberg.dev/` ?

**Comment by steakhutzeee** [comment]
Before trying with the demo api, i tried this with gotenberg 7.8:

```
- "--uno-listener-start-timeout=30s"
- "--api-timeout=300s"
```
and it worked! So actually the test with the demo API is still a thing?

**Comment by gulien** [comment]
Alright, great you’ve been able to make it work 👍
